# -*- coding: utf-8 -*-
"""Lloyds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrlUtWlaaH1hDxWqzEazTWDy0uYsDiDQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

"""# **TASK 1**

## **Excel Sheet Import**
"""

xls = pd.ExcelFile('/content/Customer_Churn_Data_Large.xlsx')
sheet_names = xls.sheet_names
print(f"The Excel file contains {len(sheet_names)} sheets.")
print(f"Sheet names: {sheet_names}")

df_demo = pd.read_excel(xls, 'Customer_Demographics')
df_trans = pd.read_excel(xls, 'Transaction_History')
df_service = pd.read_excel(xls, 'Customer_Service')
df_activity = pd.read_excel(xls, 'Online_Activity')
df_churn = pd.read_excel(xls, 'Churn_Status')

#BASIC EXPLORATION
#Create a list of your dataframes
dfs = {
    #"Demographics": df_demo,
    "Transactions": df_trans,
    "Service": df_service,
    "Activity": df_activity,
    "Churn": df_churn
}

for name, df in dfs.items():
    print(f"--- PROFILE FOR: {name} ---")
    print(f"Shape: {df.shape}")
    print(df.info())
    print(f"Unique Customers: {df['CustomerID'].nunique()}")
    print("\nDuplicated Values:")
    print(df.duplicated().sum())
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nBasic Stats:")
    display(df.describe(include='all')) # Looking at top stats
    print("-" * 30 + "\n")

"""## **Table 1 : Customer_Demographics**"""

display(df_demo.head())
display(df_demo.tail())

df_demo.shape

df_demo.info()

df_demo.describe(include='all')

df_demo.value_counts()

df_demo.nunique()

df_demo['Age'].nunique()

df_demo['Age'].unique()

df_demo.duplicated().sum()

df_demo.isnull().sum()

"""### Distribution of Age"""

plt.figure(figsize=(8, 6))
sns.histplot(df_demo['Age'], bins=20, kde=True)
plt.title('Distribution of Age in df_demo')
plt.xlabel('Age')
plt.ylabel('Count')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Value Counts for Categorical Features"""

categorical_cols = ['Gender', 'MaritalStatus', 'IncomeLevel']

for col in categorical_cols:
    plt.figure(figsize=(4, 4))
    sns.countplot(x=col, data=df_demo, palette='viridis')
    plt.title(f'Distribuion of {col} in df_demo')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.grid(axis='y', alpha=0.75)
    plt.show()

plt.figure(figsize=(10, 10))
sns.catplot(data=df_demo, x='MaritalStatus', hue='Gender', col='IncomeLevel', kind='count', palette='viridis', height=4, aspect=1.2)
plt.suptitle('Marital Status Distribution by Gender across Income Levels', y=1.02) # Adjust suptitle position
plt.xlabel('Marital Status')
plt.ylabel('Count')
#plt.tight_layout()
plt.show()

sns.barplot(data=df_demo, x='IncomeLevel', y='Age', palette='viridis')
plt.title('Income Level Distribution by Age')
plt.xlabel('Income Level')
plt.ylabel('Age')

"""### Outlier"""

def outlier(df, col_name):
    q1 = df[col_name].quantile(0.25)
    q3 = df[col_name].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    print(f"Q1: {q1}")
    print(f"Q3: {q3}")
    print(f"IQR: {iqr}")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")

    print(f"\n--- Outlier Report for {col_name} ---")
    outliers = df[(df[col_name] < lower_bound) | (df[col_name] > upper_bound)]
    print(f"Number of outliers: {len(outliers)}")
    return outliers

age_outlier = outlier(df_demo,'Age')

plt.figure(figsize=(4,2))

sns.boxplot(x=df_demo['Age'])
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

"""## **Table 2 : Transaction_History**"""

df_trans.head()

df_trans['ProductCategory'].value_counts(normalize=True)

print(f"The Transaction timeline is {df_trans['TransactionDate'].min()} to {df_trans['TransactionDate'].max()}")

amountspent_outlier = outlier(df_trans,'AmountSpent')

df_trans.groupby('ProductCategory')['AmountSpent'].mean()

df_trans.groupby('ProductCategory').agg(
    Avg_Amount_Spent=('AmountSpent', 'mean'),
    Total_Transactions=('TransactionID', 'count')
).sort_values(by='Total_Transactions', ascending=False)

df_trans.groupby('CustomerID')['AmountSpent'].sum().sort_values(ascending=False).head()

"""### Outlier"""

plt.figure(figsize=(4,2))

sns.boxplot(x=df_trans['AmountSpent'])
plt.title('Amount Spent Distribution')
plt.xlabel('Amount')
plt.ylabel('Count')
plt.show()

"""### Distribution of Product Category"""

### Distribution of Product Category

plt.figure(figsize=(5, 5))
sns.countplot(x='ProductCategory', data=df_trans, palette='viridis', order=df_trans['ProductCategory'].value_counts().index)
plt.title('Distribution of Product Category in df_trans')
plt.xlabel('Product Category')
plt.ylabel('Count')
plt.grid(axis='y', alpha=0.75)
plt.show()

### Amount Spent by Product Category

plt.figure(figsize=(6, 6))
sns.boxplot(x='ProductCategory', y='AmountSpent', data=df_trans, palette='viridis')
plt.title('Amount Spent Distribution by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Amount Spent')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Daily Transaction Trends"""

daily_transactions = df_trans.groupby('TransactionDate').agg(
    Total_Transactions=('TransactionID', 'count'),
    Total_Amount_Spent=('AmountSpent', 'sum')
).reset_index()

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
sns.lineplot(x='TransactionDate', y='Total_Transactions', data=daily_transactions)
plt.title('Total Daily Transactions')
plt.xlabel('Date')
plt.ylabel('Number of Transactions')
plt.grid(axis='y', alpha=0.75)

plt.subplot(1, 2, 2)
sns.lineplot(x='TransactionDate', y='Total_Amount_Spent', data=daily_transactions)
plt.title('Total Daily Amount Spent')
plt.xlabel('Date')
plt.ylabel('Amount Spent')
plt.grid(axis='y', alpha=0.75)

plt.tight_layout()
plt.show()

"""### Monthly Transaction Trends"""

df_trans['Month'] = df_trans['TransactionDate'].dt.month_name()
monthly_transactions = df_trans.groupby('Month').agg(
    Total_Transactions=('TransactionID', 'count'),
    Total_Amount_Spent=('AmountSpent', 'sum')
).reset_index()

# Order months correctly for plotting
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
monthly_transactions['Month'] = pd.Categorical(monthly_transactions['Month'], categories=month_order, ordered=True)
monthly_transactions = monthly_transactions.sort_values('Month')

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
sns.barplot(x='Month', y='Total_Transactions', data=monthly_transactions, palette='viridis')
plt.title('Total Monthly Transactions')
plt.xlabel('Month')
plt.ylabel('Number of Transactions')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.75)

plt.subplot(1, 2, 2)
sns.barplot(x='Month', y='Total_Amount_Spent', data=monthly_transactions, palette='magma')
plt.title('Total Monthly Amount Spent')
plt.xlabel('Month')
plt.ylabel('Amount Spent')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.75)

plt.tight_layout()
plt.show()

sns.histplot(data=df_trans, x='AmountSpent', bins=10, kde=True)
plt.title('Distribution of Amount Spent in df_trans by ProductCategory')
plt.xlabel('Amount Spent')
plt.ylabel('Count')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""## **Table 3 : Customer_Service**"""

df_service.head()

df_service['InteractionType'].value_counts()

df_service['ResolutionStatus'].value_counts()

print(f"The Service timeline is {df_service['InteractionDate'].min()} to {df_service['InteractionDate'].max()}")

df_service.groupby('CustomerID')['InteractionID'].count().sort_values(ascending=False).head()

"""### Distribution"""

plt.figure(figsize=(5, 7))
sns.countplot(x='InteractionType', hue='ResolutionStatus', data=df_service, palette='viridis')
plt.title('Interaction Type by Resolution Status in df_service')
plt.xlabel('Interaction Type')
plt.ylabel('Count')
plt.grid(axis='y', alpha=0.75)
plt.legend(title='Resolution Status')
plt.show()

cols = ['InteractionType', 'ResolutionStatus']

for col in cols:
    plt.figure(figsize=(4, 4))
    sns.countplot(x=col, data=df_service, palette='viridis', order=df_service[col].value_counts().index)
    plt.title(f'Distribution of {col} in df_service')
    plt.xlabel(col)
    plt.ylabel('count')
    plt.grid(axis='y', alpha=0.5)
    plt.show()

"""### Daily Interaction Trends"""

daily_interactions_service = df_service.groupby('InteractionDate').agg(
    Total_Interactions=('InteractionID', 'count')
).reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(x='InteractionDate', y='Total_Interactions', data=daily_interactions_service)
plt.title('Total Daily Customer Service Interactions')
plt.xlabel('Date')
plt.ylabel('Number of Interactions')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

"""### Monthly Interaction Trends"""

df_service['Month'] = df_service['InteractionDate'].dt.month_name()
monthly_interactions_service = df_service.groupby('Month').agg(
    Total_Interactions=('InteractionID', 'count')
).reset_index()

# Order months correctly for plotting
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
monthly_interactions_service['Month'] = pd.Categorical(monthly_interactions_service['Month'], categories=month_order, ordered=True)
monthly_interactions_service = monthly_interactions_service.sort_values('Month')

plt.figure(figsize=(6, 6))
sns.barplot(x='Month', y='Total_Interactions', data=monthly_interactions_service, palette='viridis')
plt.title('Total Monthly Customer Service Interactions')
plt.xlabel('Month')
plt.ylabel('Number of Interactions')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

df_service['Month'] = df_service['InteractionDate'].dt.month_name()
monthly_interaction_types = df_service.groupby(['Month', 'InteractionType']).size().unstack(fill_value=0).reset_index()

# Order months correctly for plotting
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
monthly_interaction_types['Month'] = pd.Categorical(monthly_interaction_types['Month'], categories=month_order, ordered=True)
monthly_interaction_types = monthly_interaction_types.sort_values('Month')

monthly_interaction_types.set_index('Month').plot(kind='bar', stacked=False, figsize=(7, 4), colormap='viridis')
plt.title('Monthly Distribution of Customer Service Interaction Types')
plt.xlabel('Month')
plt.ylabel('Number of Interactions')
plt.xticks(rotation=45)
plt.legend(title='Interaction Type')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

"""## **Table 4 : Online_Activity**"""

df_activity.head()

df_activity['ServiceUsage'].value_counts()

print(f"The Activity timeline is {df_activity['LastLoginDate'].min()} to {df_activity['LastLoginDate'].max()}")

sns.histplot(data=df_activity, x='LoginFrequency', bins=15, kde=True)
plt.title('Distribution of Login Frequency in df_activity')
plt.xlabel('Login Frequency')
plt.ylabel('Count')

plt.figure(figsize=(4, 4))
sns.barplot(x='ServiceUsage', y='LoginFrequency', data=df_activity, palette='viridis')
plt.title('Login Frequency by Service Usage')
plt.xlabel('Service Usage')
plt.ylabel('Login Frequency')

df_activity['Month'] = df_activity['LastLoginDate'].dt.month_name()
monthly_login_trends = df_activity.groupby(['Month', 'ServiceUsage'])['LoginFrequency'].mean().reset_index()

# Order months correctly for plotting
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
monthly_login_trends['Month'] = pd.Categorical(monthly_login_trends['Month'], categories=month_order, ordered=True)
monthly_login_trends = monthly_login_trends.sort_values('Month')

plt.figure(figsize=(10, 5))
sns.barplot(x='Month', y='LoginFrequency', hue='ServiceUsage', data=monthly_login_trends, palette='viridis')
plt.title('Average Login Frequency by Month and Service Usage')
plt.xlabel('Month')
plt.ylabel('Average Login Frequency')
plt.xticks(rotation=45)
plt.legend(title='Service Usage')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

"""## **Table 5 : Churn_Status**"""

df_churn.head()

df_churn['ChurnStatus'].value_counts()

sns.countplot(x='ChurnStatus', data=df_churn, palette='viridis')
plt.title('Distribution of Churn Status in df_churn')
plt.xlabel('Churn Status')
plt.ylabel('Count')

"""## **Aggregation**"""

today = pd.to_datetime('2024-01-01')
today

"""### Sheet A: Online_Activity"""

#Sheet A: Online_Activity (Recency & Frequency)

df_activity['LastLoginDate'] = pd.to_datetime(df_activity['LastLoginDate'])

# Create the new column
df_activity['Days_Since_Last_Login'] = (today - df_activity['LastLoginDate']).dt.days

df_activity.head()

# Aggregation: 1 row per customer
# We take the SUM of logins (Frequency) and the MIN of days since (the most recent login)
df_activity_agg = df_activity.groupby('CustomerID').agg(
    Total_Logins=('LoginFrequency', 'sum'),
    Recency_Login=('Days_Since_Last_Login', 'min'),
    Service=('ServiceUsage', lambda x: x.mode()[0] if not x.mode().empty else None),
    Last_Login_Month=('Month', lambda x: x.mode()[0] if not x.mode().empty else None)
).reset_index()

df_activity_agg.head()

"""### Sheet B: Transaction_History"""

df_trans.head(10)

#Sheet B: Transaction_History (Monetary & Frequency)

df_trans_agg = df_trans.groupby('CustomerID').agg(
    Total_spend = ('AmountSpent','sum'),
    Transaction_Count = ('TransactionID','count'),
    Most_Frequent_Product_Category=('ProductCategory', lambda x: x.mode()[0] if not x.mode().empty else None),
    Distinct_Product_Categories=('ProductCategory','nunique')
).reset_index()

df_trans_agg.head()

if 'TransactionDate' in df_trans.columns and not pd.api.types.is_datetime64_any_dtype(df_trans['TransactionDate']):
    df_trans['TransactionDate'] = pd.to_datetime(df_trans['TransactionDate'])
if 'Month' not in df_trans.columns:
    df_trans['Month'] = df_trans['TransactionDate'].dt.month_name()

def get_most_active_month_complex(df_customer_group):
    if df_customer_group.empty:
        return None

    # Calculate transaction counts per month
    monthly_counts = df_customer_group.groupby('Month').size()

    # Get months with the highest transaction count
    max_count = monthly_counts.max()
    most_frequent_months = monthly_counts[monthly_counts == max_count].index.tolist()

    if len(most_frequent_months) == 1:
        # No tie in frequency, return that month
        return most_frequent_months[0]
    else:
        # Tie in frequency, use amount spent as tie-breaker
        monthly_spend = df_customer_group.groupby('Month')['AmountSpent'].sum()
        # Filter spend for only the most frequent months
        tied_months_spend = monthly_spend[monthly_spend.index.isin(most_frequent_months)]
        # Return the month with the highest spend among the tied months
        return tied_months_spend.idxmax()

# Define a helper function to apply to each customer group
def aggregate_transaction_months(group):
    num_active_months = group['Month'].nunique()
    most_active_month = get_most_active_month_complex(group)
    return pd.Series({
        'Number_of_Active_Months': num_active_months,
        'Most_Active_Month': most_active_month
    })

# Use .apply() to pass the entire group DataFrame to the helper function
df_trans_month_agg = df_trans.groupby('CustomerID').apply(aggregate_transaction_months, include_groups=False).reset_index()

df_trans_month_agg.head()

"""### Sheet C: Customer_Service"""

df_service.head(10)

#Sheet C: Customer_Service (The "Friction" Metric)

df_service_agg = df_service.groupby('CustomerID').agg(
    Total_Service_Calls=('InteractionID', 'count'),
    Unresolved_Issues=('ResolutionStatus', lambda x: (x == 'Unresolved').sum())
).reset_index()

df_service_agg.head(6)

"""## **Merge**"""

# 1. Start with the 'Core' of the bank: Demographics
master_df = df_demo.copy()

master_df.head()

df_activity_agg.head()

df_trans_agg.head()

df_trans_month_agg.head()

df_service_agg.head()

df_churn.head()

# 2. Add the Behavior (Activity, Transactions, Service)
master_df = master_df.merge(df_activity_agg, on='CustomerID', how='left')
master_df = master_df.merge(df_trans_agg, on='CustomerID', how='left')
master_df = master_df.merge(df_trans_month_agg, on='CustomerID', how='left') # Merge the monthly aggregation dataframe
master_df = master_df.merge(df_service_agg, on='CustomerID', how='left')

# 3. Add the Target (Did they churn?)
master_df = master_df.merge(df_churn, on='CustomerID', how='left')

# Fill missing counts/sums with 0
cols_to_fix = ['Total_Logins', 'Total_spend', 'Transaction_Count', 'Total_Service_Calls', 'Unresolved_Issues']
master_df[cols_to_fix] = master_df[cols_to_fix].fillna(0)

# For Recency, if they never logged in, we'll set it to a very high number (e.g., 999 days)
master_df['Recency_Login'] = master_df['Recency_Login'].fillna(999)

print("Master Table is Ready!")
master_df.head()

"""# **Final Dataset**"""

master_df.head()

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=master_df)

master_df.isnull().sum()

display(master_df.describe())

"""## **1. Correlation Matrix**"""

correlation_matrix = master_df.corr(numeric_only=True)
display(correlation_matrix)

plt.figure(figsize=(10, 8))
numeric_df = master_df.select_dtypes(include=[np.number])
correlation_matrix = numeric_df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Master Table Features')
plt.savefig('correlation_heatmap.png')

"""## **2. Categorical Patterns/Crosstabs**"""

# Crosstab for Gender vs ChurnStatus
crosstab_gender = pd.crosstab(master_df['Gender'], master_df['ChurnStatus'], normalize='index', margins=True)
display(crosstab_gender)

# Visualize Gender vs ChurnStatus
plt.figure(figsize=(6, 4))
sns.countplot(data=master_df, x='Gender', hue='ChurnStatus', palette='viridis')
plt.title('Churn Status by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.legend(title='ChurnStatus', labels=['No Churn', 'Churn'])
plt.grid(axis='y', alpha=0.75)
plt.show()

# Crosstab for MaritalStatus vs ChurnStatus
crosstab_marital_status = pd.crosstab(master_df['MaritalStatus'], master_df['ChurnStatus'], normalize='index', margins=True)
display(crosstab_marital_status)

# Visualize MaritalStatus vs ChurnStatus
plt.figure(figsize=(8, 5))
sns.countplot(data=master_df, x='MaritalStatus', hue='ChurnStatus', palette='viridis')
plt.title('Churn Status by Marital Status')
plt.xlabel('Marital Status')
plt.ylabel('Count')
plt.legend(title='ChurnStatus', labels=['No Churn', 'Churn'])
plt.grid(axis='y', alpha=0.75)
plt.show()

# Crosstab for IncomeLevel vs ChurnStatus
crosstab_income_level = pd.crosstab(master_df['IncomeLevel'], master_df['ChurnStatus'], normalize='index', margins=True)
display(crosstab_income_level)

# Visualize IncomeLevel vs ChurnStatus
plt.figure(figsize=(8, 5))
sns.countplot(data=master_df, x='IncomeLevel', hue='ChurnStatus', palette='viridis')
plt.title('Churn Status by Income Level')
plt.xlabel('Income Level')
plt.ylabel('Count')
plt.legend(title='ChurnStatus', labels=['No Churn', 'Churn'])
plt.grid(axis='y', alpha=0.75)
plt.show()

remaining_categorical_features = [
    'Service',
    'Last_Login_Month',
    'Most_Frequent_Product_Category',
    'Most_Active_Month'
]

for feature in remaining_categorical_features:
    print(f"\n--- Analyzing {feature} vs ChurnStatus ---")

    # Create normalized crosstab for churn rates
    normalized_crosstab = pd.crosstab(master_df[feature], master_df['ChurnStatus'], normalize='index')
    print("\nNormalized Crosstab (Churn Rates):")
    display(normalized_crosstab)

"""## **3. Deep Dive & Intersection Analysis**

### **1. Identifying Patterns**
"""

crosstab_income_service = pd.crosstab([master_df['IncomeLevel'], master_df['Service']], master_df['ChurnStatus'], normalize='index')
crosstab_income_service_sorted = crosstab_income_service.sort_values(by=1, ascending=False)
display(crosstab_income_service_sorted)

crosstab_marital_gender = pd.crosstab([master_df['MaritalStatus'], master_df['Gender']], master_df['ChurnStatus'], normalize='index')
crosstab_marital_gender_sorted = crosstab_marital_gender.sort_values(by=1, ascending=False)
display(crosstab_marital_gender_sorted)

crosstab_prCat_income = pd.crosstab([master_df['Most_Frequent_Product_Category'], master_df['IncomeLevel']], master_df['ChurnStatus'], normalize='index')
crosstab_prCat_income_sorted = crosstab_prCat_income.sort_values(by=1, ascending=False)
display(crosstab_prCat_income_sorted)

"""### **2. Identifying Anomalies**"""

print('--- Anomalies: Churned despite being in a low-churn group ---')
# Based on crosstab_income_service, 'High Income' and 'Website' service usage has a low churn rate.
low_churn_group_churned = master_df[(master_df['IncomeLevel'] == 'High') &
                                    (master_df['Service'] == 'Website') &
                                    (master_df['ChurnStatus'] == 1)]
print(f"Number of customers with High Income and Website usage who churned: {len(low_churn_group_churned)}")
display(low_churn_group_churned.head())

print('\n--- Anomalies: Did not churn despite being in a high-churn group ---')
# Based on crosstab_income_service, 'Medium Income' and 'Mobile App' service usage has a high churn rate.
high_churn_group_not_churned = master_df[(master_df['IncomeLevel'] == 'Medium') &
                                        (master_df['Service'] == 'Mobile App') &
                                        (master_df['ChurnStatus'] == 0)]
print(f"Number of customers with Medium Income and Mobile App usage who did not churn: {len(high_churn_group_not_churned)}")
display(high_churn_group_not_churned.head())

"""### **3.Exploring Non-Linear Patterns: Age vs. Churn**"""

plt.figure(figsize=(10, 6))
sns.kdeplot(data=master_df, x='Age', hue='ChurnStatus', fill=True, common_norm=False, palette='viridis')
plt.title('Age Distribution by Churn Status (KDE Plot)')
plt.xlabel('Age')
plt.ylabel('Density')
plt.legend(title='Churn Status', labels=['No Churn', 'Churn'])
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=master_df, x='Total_spend', hue='ChurnStatus', fill=True, common_norm=False, palette='magma')
plt.title('Total Spend Distribution by Churn Status (KDE Plot)')
plt.xlabel('Total Spend')
plt.ylabel('Density')
plt.legend(title='Churn Status', labels=['No Churn', 'Churn'])
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=master_df, x='Total_Logins', hue='ChurnStatus', fill=True, common_norm=False, palette='coolwarm')
plt.title('Total Login Frequency Distribution by Churn Status (KDE Plot)')
plt.xlabel('Total Logins')
plt.ylabel('Density')
plt.legend(title='Churn Status', labels=['No Churn', 'Churn'])
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""## **Statistical Tests**

### **1. The Chi-Square Test (Categories)**
"""

from scipy.stats import chi2_contingency

# Test Service vs Churn
contingency_table = pd.crosstab(master_df['Service'], master_df['ChurnStatus'])
chi2, p, dof, ex = chi2_contingency(contingency_table)

print(f"Chi-Square P-value: {p}")
if p < 0.05:
    print("Significant: Service Usage is a real predictor of churn.")
else:
    print("Not significant: Service Usage is NOT a real predictor of churn.")

from scipy.stats import chi2_contingency

# Test IncomeLevel vs ChurnStatus
contingency_table_income = pd.crosstab(master_df['IncomeLevel'], master_df['ChurnStatus'])
chi2_income, p_income, dof_income, ex_income = chi2_contingency(contingency_table_income)

print(f"Chi-Square P-value for IncomeLevel vs ChurnStatus: {p_income}")
if p_income < 0.05:
    print("Significant: IncomeLevel is a real predictor of churn.")
else:
    print("Not significant: IncomeLevel is NOT a real predictor of churn.")

from scipy.stats import chi2_contingency

# Test Gender vs ChurnStatus
contingency_table_gender = pd.crosstab(master_df['Gender'], master_df['ChurnStatus'])
chi2_gender, p_gender, dof_gender, ex_gender = chi2_contingency(contingency_table_gender)

print(f"Chi-Square P-value for Gender vs ChurnStatus: {p_gender}")
if p_gender < 0.05:
    print("Significant: Gender is a real predictor of churn.")
else:
    print("Not significant: Gender is NOT a real predictor of churn.")

from scipy.stats import chi2_contingency

# Test MaritalStatus vs ChurnStatus
contingency_table_marital = pd.crosstab(master_df['MaritalStatus'], master_df['ChurnStatus'])
chi2_marital, p_marital, dof_marital, ex_marital = chi2_contingency(contingency_table_marital)

print(f"Chi-Square P-value for MaritalStatus vs ChurnStatus: {p_marital}")
if p_marital < 0.05:
    print("Significant: MaritalStatus is a real predictor of churn.")
else:
    print("Not significant: MaritalStatus is NOT a real predictor of churn.")

from scipy.stats import chi2_contingency

remaining_categorical_features_to_test = [
    'Last_Login_Month',
    'Most_Frequent_Product_Category',
    'Most_Active_Month'
]

for feature in remaining_categorical_features_to_test:
    print(f"\n--- Chi-Square Test for {feature} vs ChurnStatus ---")
    contingency_table = pd.crosstab(master_df[feature], master_df['ChurnStatus'])
    chi2, p, dof, ex = chi2_contingency(contingency_table)

    print(f"Chi-Square P-value: {p}")
    if p < 0.05:
        print(f"Significant: {feature} is a real predictor of churn.")
    else:
        print(f"Not significant: {feature} is NOT a real predictor of churn.")

"""### **2. The t-test (Numericals)**"""

from scipy.stats import ttest_ind

numerical_features_to_test = [
    'Age', 'Total_Logins', 'Recency_Login', 'Total_spend', 'Transaction_Count',
    'Distinct_Product_Categories', 'Number_of_Active_Months', 'Total_Service_Calls', 'Unresolved_Issues'
]

for feature in numerical_features_to_test:
    # Separate data into churned and non-churned groups
    churned = master_df[master_df['ChurnStatus'] == 1][feature]
    not_churned = master_df[master_df['ChurnStatus'] == 0][feature]

    # Perform independent samples t-test
    stat, p_value = ttest_ind(churned, not_churned, equal_var=False) # Welch's t-test, more robust when variance is unequal

    print(f"\n--- T-test for {feature} vs ChurnStatus ---")
    print(f"Mean of {feature} (Churned): {churned.mean():.2f}")
    print(f"Mean of {feature} (Not Churned): {not_churned.mean():.2f}")
    print(f"T-statistic: {stat:.2f}")
    print(f"P-value: {p_value:.4f}")

    if p_value < 0.05:
        print(f"Significant: There is a statistically significant difference in {feature} between churned and non-churned customers.")
    else:
        print(f"Not significant: No statistically significant difference in {feature} between churned and non-churned customers.")

"""## **Class Imbalance Check**"""

print(master_df['ChurnStatus'].value_counts())
print(master_df['ChurnStatus'].value_counts(normalize=True))

plt.figure(figsize=(3, 3))
sns.countplot(x='ChurnStatus', data=master_df, palette='viridis')
plt.title('Distribution of Churn Status')
plt.xlabel('Churn Status')
plt.ylabel('Count')
plt.show()

"""## **Feature Engineering**"""

# --- STEP: RFM FEATURE ENGINEERING ---

# 1. Recency (Days since last login) - Higher is better (5)
master_df['R_Score'] = pd.qcut(master_df['Recency_Login'], 5, labels=[5, 4, 3, 2, 1])

# 2. Frequency (Transaction Count) - Higher is better (5)
master_df['F_Score'] = pd.qcut(master_df['Transaction_Count'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])

# 3. Monetary (Total Spend) - Higher is better (5)
master_df['M_Score'] = pd.qcut(master_df['Total_spend'], 5, labels=[1, 2, 3, 4, 5])

# 4. Combine into a single RFM Score
# We convert them to strings to create a '555' or '111' style code
master_df['RFM_Sum'] = master_df['R_Score'].astype(int) + master_df['F_Score'].astype(int) + master_df['M_Score'].astype(int)

# --- STEP: INTERACTION FEATURES ---
master_df['Login_Consistency'] = master_df['Total_Logins'] / (master_df['Recency_Login'] + 1)
master_df['Spend_Efficiency'] = master_df['Total_spend'] / (master_df['Transaction_Count'] + 1)
master_df['Service_Friction'] = master_df['Unresolved_Issues'] / (master_df['Total_Service_Calls'] + 1)

master_df.head()

"""## **Data Preprocessing for Machine Learning**"""

master_df.columns.tolist()

master_df.info()

master_df['R_Score'] = master_df['R_Score'].astype(int)
master_df['F_Score'] = master_df['F_Score'].astype(int)
master_df['M_Score'] = master_df['M_Score'].astype(int)

"""### **Identifying Feature Types**"""

# Drop CustomerID as it's an identifier and not a feature for the model
X = master_df.drop(['CustomerID', 'Total_spend', 'Distinct_Product_Categories', 'ChurnStatus'], axis=1)
y = master_df['ChurnStatus']

categorical_features = X.select_dtypes(include='object').columns.tolist()
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

print(f"Categorical Features: {categorical_features}")
print(f"Numerical Features: {numerical_features}")

"""### **Encoding Categorical Features**"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Create a column transformer for one-hot encoding categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # Keep numerical features as they are for now
)

# Apply the preprocessing to X
X_encoded = preprocessor.fit_transform(X)

# Get feature names after one-hot encoding
# This creates new column names based on the original category and its values
encoded_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
all_feature_names = list(encoded_feature_names) + numerical_features

# Convert the processed data back to a DataFrame
X_processed = pd.DataFrame(X_encoded, columns=all_feature_names)

print("Shape of original X:", X.shape)
print("Shape of X after one-hot encoding:", X_processed.shape)
print("First 5 rows of processed X:")
display(X_processed.head())

"""### **Scaling Numerical Features**"""

from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical features in X_processed
X_processed[numerical_features] = scaler.fit_transform(X_processed[numerical_features])

print("Numerical features in X_processed scaled successfully.")
print("First 5 rows of processed X with scaled numerical features:")
display(X_processed.head())

X_processed.shape

y.head()

y.shape

"""# **TASK 2**

## **Data Splitting**
"""

from sklearn.model_selection import train_test_split

# X_processed is your scaled/encoded features, y is your target
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Data split successfully. Training rows: {len(X_train)}, Test rows: {len(X_test)}")

"""## **1. Baseline Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Initialize and train
log_baseline = LogisticRegression(max_iter=1000, random_state=42)
log_baseline.fit(X_train, y_train)

# Predict
y_pred_log = log_baseline.predict(X_test)
y_prob_log = log_baseline.predict_proba(X_test)[:, 1]

"""### **Model Evaluation LR**"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred_log)
precision = precision_score(y_test, y_pred_log)
recall = recall_score(y_test, y_pred_log)
f1 = f1_score(y_test, y_pred_log)

print("--- BASELINE: LOGISTIC REGRESSION ---")
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log))
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_log):.2f}")

"""## **2. Advanced Random Forest**"""

from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# 1. Apply SMOTE ONLY to training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# 2. Initialize Random Forest
rf_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced', # <--- THIS IS THE KEY
    max_depth=10,
    random_state=42
)

# 3. Cross-Validation (on resampled training data to check stability)
cv_scores = cross_val_score(rf_model, X_train_resampled, y_train_resampled, cv=5, scoring='f1')
print(f"RF Cross-Val F1 Score: {cv_scores.mean():.2f} (+/- {cv_scores.std():.2f})")

# 4. Train the final model on resampled training data
rf_model.fit(X_train_resampled, y_train_resampled)

"""### **Model Evaluation RF**"""

# Predict on the PURE test set
y_probs = rf_model.predict_proba(X_test)[:, 1]

# Force the model to be aggressive
y_pred_new = (y_probs >= 0.35).astype(int)

accuracy_new = accuracy_score(y_test, y_pred_new)
precision_new = precision_score(y_test, y_pred_new)
recall_new = recall_score(y_test, y_pred_new)
f1_new = f1_score(y_test, y_pred_new)

print("--- ADVANCED: RANDOM FOREST ---")
print(f"Accuracy: {accuracy_new:.2f}")
print(f"Precision: {precision_new:.2f}")
print(f"Recall: {recall_new:.2f}")
print(f"F1-Score: {f1_new}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_new))

print("--- Aggressive Threshold Results ---")
print(classification_report(y_test, y_pred_new))

print(f"ROC-AUC: {roc_auc_score(y_test, y_probs):.2f}")

"""#### **Random Forest Feature Importance**"""

import pandas as pd
import matplotlib.pyplot as plt

importances = rf_model.feature_importances_
feature_names = X_train.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 5))
plt.barh(feature_importance_df['Feature'][:10], feature_importance_df['Importance'][:10])
plt.title("Top 10 Features")
plt.show()

feature_importance_df.head(10)

"""### **Hyperparameter Tuning RF**"""

from sklearn.model_selection import RandomizedSearchCV

# 1. Filter X to only include your Top 10 Features
# (Update this list based on your importance plot: Recency, Total Logins, Age, etc.)
top_10_features_rf = [
    'Service_Website', 'Spend_Efficiency', 'MaritalStatus_Married', 'Age',
    'Total_Logins', 'Login_Consistency', 'Recency_Login', 'Gender_F',
    'Gender_M', 'Service_Mobile App'
]

X_top = X_train[top_10_features_rf]
X_test_top = X_test[top_10_features_rf]

# 2. Define the Parameter Grid
# We are testing different 'depths' and 'strengths' of the forest
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'class_weight': ['balanced', 'balanced_subsample']
}

# 3. Initialize RandomizedSearchCV
# We use scoring='roc_auc' because we want to improve that 0.49 score
randomized_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_grid, # Corrected argument name
    cv=5,
    scoring='roc_auc',
    verbose=1,
    n_jobs=-1
)

# 4. Run the Search
print("Starting Hyperparameter Tuning RF...")
randomized_search.fit(X_top, y_train)

# 5. Extract the Best Model
best_rf = randomized_search.best_estimator_
print(f"\nBest Parameters: {randomized_search.best_params_}")

# 6. Final Evaluation
y_probs_tuned = best_rf.predict_proba(X_test_top)[:, 1]
y_pred_tuned = (y_probs_tuned >= 0.35).astype(int) # Keeping your aggressive threshold

print("\n--- TUNED MODEL EVALUATION (TOP 10 FEATURES) ---")
print(f"ROC-AUC: {roc_auc_score(y_test, y_probs_tuned):.2f}")

accuracy_score = accuracy_score(y_test, y_pred_tuned)
precision_score = precision_score(y_test, y_pred_tuned)
recall_score = recall_score(y_test, y_pred_tuned)
f1_score = f1_score(y_test, y_pred_tuned)

print(f"Accuracy: {accuracy_score:.2f}")
print(f"Precision: {precision_score:.2f}")
print(f"Recall: {recall_score:.2f}")
print(f"F1-Score: {f1_score:.2f}")

print(confusion_matrix(y_test, y_pred_tuned))
print(classification_report(y_test, y_pred_tuned))
print(f"Final Tuned ROC-AUC: {roc_auc_score(y_test, y_probs_tuned):.2f}")

"""## **3. XGBoost**"""

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

# 1. Apply SMOTE ONLY to training data (copied from previous section)
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Calculate scale_pos_weight for handling class imbalance with XGBoost
# It's recommended to use sum(negative instances) / sum(positive instances)
neg_count = y_train_resampled.value_counts()[0] # Count of non-churn (0)
pos_count = y_train_resampled.value_counts()[1] # Count of churn (1)
scale_pos_weight_value = neg_count / pos_count

# Initialize XGBoost Classifier
xgb_model = XGBClassifier(
    objective='binary:logistic', # For binary classification
    use_label_encoder=False,     # Suppress warning for older sklearn versions
    eval_metric='logloss',       # Evaluation metric for binary classification
    n_estimators=200,
    max_depth=10,
    learning_rate=0.1,
    subsample=0.7,
    colsample_bytree=0.7,
    gamma=0.1,
    scale_pos_weight=scale_pos_weight_value, # Handle imbalance, alternative to class_weight
    random_state=42
)

# Cross-Validation on resampled training data
cv_scores_xgb = cross_val_score(xgb_model, X_train_resampled, y_train_resampled, cv=5, scoring='f1', n_jobs=-1)
print(f"XGBoost Cross-Val F1 Score: {cv_scores_xgb.mean():.2f} (+/- {cv_scores_xgb.std():.2f})")

# Train the final XGBoost model on resampled training data
xgb_model.fit(X_train_resampled, y_train_resampled)

"""### **Model Evaluation XGB**"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score

# Predict probabilities on the PURE test set
y_probs_xgb = xgb_model.predict_proba(X_test)[:, 1]

# Apply the aggressive threshold (0.35) for prediction
y_pred_xgb = (y_probs_xgb >= 0.35).astype(int)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)
roc_auc_xgb = roc_auc_score(y_test, y_probs_xgb)

print("--- ADVANCED: XGBOOST MODEL ---")
print(f"Accuracy: {accuracy_xgb:.2f}")
print(f"Precision: {precision_xgb:.2f}")
print(f"Recall: {recall_xgb:.2f}")
print(f"F1-Score: {f1_xgb:.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

print("--- Aggressive Threshold Results ---")
print(classification_report(y_test, y_pred_xgb))

print(f"ROC-AUC: {roc_auc_xgb:.2f}")

"""#### **XGBoost Feature Importance**"""

import pandas as pd
import matplotlib.pyplot as plt

# Get feature importances from the trained XGBoost model
importances_xgb = xgb_model.feature_importances_
feature_names_xgb = X_train.columns # Use the original feature names from X_train

# Create a DataFrame for better visualization
feature_importance_df_xgb = pd.DataFrame({'Feature': feature_names_xgb, 'Importance': importances_xgb})
feature_importance_df_xgb = feature_importance_df_xgb.sort_values(by='Importance', ascending=False)

# Display the top 10 features
print("Top 10 XGBoost Features:")
display(feature_importance_df_xgb.head(10))

# Plot the top 10 features
plt.figure(figsize=(10, 5))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df_xgb.head(10), palette='viridis')
plt.title("Top 10 XGBoost Features by Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

"""### **Hyperparameter Tuning XGB**"""

from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score

# 1. Filter X to only include your Top 10 Features
# (Update this list based on your importance plot: Recency, Total Logins, Age, etc.)
top_10_features_xgb = [
    'MaritalStatus_Married', 'IncomeLevel_Low', 'Service_Website', 'Last_Login_Month_May',
    'Most_Active_Month_October', 'Service_Mobile App', 'MaritalStatus_Single', 'MaritalStatus_Divorced',
    'Gender_M', 'Most_Active_Month_May'
]

X_top = X_train[top_10_features_xgb]
X_test_top = X_test[top_10_features_xgb]

# Recalculate scale_pos_weight for tuning, using the resampled training data if SMOTE is applied for tuning
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train[top_10_features_xgb], y_train)
neg_count = y_train_resampled.value_counts()[0]
pos_count = y_train_resampled.value_counts()[1]
scale_pos_weight_value = neg_count / pos_count

# 2. Define the Parameter Grid with XGBoost-specific parameters
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 10],
    'learning_rate': [0.01, 0.1, 0.2],
    #'subsample': [0.7, 0.8, 0.9],
    #'colsample_bytree': [0.7, 0.8, 0.9],
    #'gamma': [0, 0.1, 0.2],
    #'min_child_weight': [1, 3, 5],
    'scale_pos_weight': [scale_pos_weight_value] # Use the calculated value or experiment with a range
}

# 3. Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=XGBClassifier(
        objective='binary:logistic',
        eval_metric='logloss',
        use_label_encoder=False, # Suppress warning
        random_state=42
    ),
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc',
    verbose=1,
    n_jobs=-1
)

# 4. Run the Search
print("Starting Hyperparameter Tuning XGB...")
# Fit on the original training data (X_top, y_train) if SMOTE is handled via scale_pos_weight
# If SMOTE resampled data was used, fit on X_train_resampled, y_train_resampled
grid_search_xgb.fit(X_top, y_train)

# 5. Extract the Best Model
best_xgb = grid_search_xgb.best_estimator_
print(f"\nBest Parameters: {grid_search_xgb.best_params_}")

# 6. Final Evaluation
y_probs_tuned = best_xgb.predict_proba(X_test_top)[:, 1]
y_pred_tuned = (y_probs_tuned >= 0.35).astype(int) # Keeping your aggressive threshold

print("\n--- TUNED MODEL EVALUATION (TOP 10 FEATURES) ---")
print(f"ROC-AUC: {roc_auc_score(y_test, y_probs_tuned):.2f}")

accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
precision_tuned = precision_score(y_test, y_pred_tuned)
recall_tuned = recall_score(y_test, y_pred_tuned)
f1_tuned = f1_score(y_test, y_pred_tuned)

print(f"Accuracy: {accuracy_tuned:.2f}")
print(f"Precision: {precision_tuned:.2f}")
print(f"Recall: {recall_tuned:.2f}")
print(f"F1-Score: {f1_tuned:.2f}")

print(confusion_matrix(y_test, y_pred_tuned))
print(classification_report(y_test, y_pred_tuned))
print(f"Final Tuned ROC-AUC: {roc_auc_score(y_test, y_probs_tuned):.2f}")

"""## **Pipeline**"""

from sklearn.base import BaseEstimator, TransformerMixin

class LloydsFeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self, top_features):
        self.top_features = top_features

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        # The features 'Login_Consistency' and 'Spend_Efficiency' are already created earlier in the notebook
        # and are expected to be present in the X DataFrame passed to the pipeline.
        # This transformer will now only select the top features.
        return X[self.top_features]

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import joblib

# 1. Define your winning features from the grid search
top_10_features = [
    'Service_Website', 'Spend_Efficiency', 'MaritalStatus_Married', 'Age',
    'Total_Logins', 'Login_Consistency', 'Recency_Login', 'Gender_F',
    'Gender_M', 'Service_Mobile App'
]

# 2. Build the "Assembly Line"
production_pipeline = Pipeline([
    ('engineer', LloydsFeatureEngineer(top_features=top_10_features)),
    ('scaler', StandardScaler()),
    ('classifier', best_xgb) # This is the model you just tuned!
])

# 3. Fit it one last time on the training data
production_pipeline.fit(X_train, y_train)

# 4. Save it as a physical file
joblib.dump(production_pipeline, 'lloyds_churn_prod_v1.pkl')
print("Model Exported Successfully!")

# Create a "New Customer" (Raw Data)
new_customer = pd.DataFrame([{
    'Total_Logins': 5,
    'Recency_Login': 20,
    'Spend_Efficiency': 500 / (2 + 1), # Calculate Spend_Efficiency based on Total_Spend and Transaction_Count
    'Age': 25,
    'Service_Website': 1,
    'MaritalStatus_Married': 0,
    'Gender_F': 1,
    'Gender_M': 0,
    'Service_Mobile App': 0,
    'Login_Consistency': 5 / (20 + 1) # Calculate Login_Consistency based on Total_Logins and Recency_Login
}])

# Ensure the columns match the `top_10_features` order for consistency
new_customer = new_customer[top_10_features]

# Load the model back up (just like a production server would)
deployed_model = joblib.load('lloyds_churn_prod_v1.pkl')

# Get the prediction
risk_probability = deployed_model.predict_proba(new_customer)[:, 1][0]
prediction = "ACTION REQUIRED" if risk_probability >= 0.35 else "STABLE"

print(f"Customer Churn Risk: {risk_probability:.2%}")
print(f"Recommendation: {prediction}")

